[package]
name = "axum_tut"
version = "0.1.0"
edition = "2021"

[alias]
itest = "test"

[dependencies]
anyhow = "1"
# axum = "0.7.7"
axum = "0.6"
tokio = { version = "1", features = ["full"] }


[dev-dependencies]
httpc-test = "0.1.1"
