mod arrays;
mod atomic_reference_counter;
mod bank;
mod closures;
mod conditions;
mod enumerations;
mod enums;
mod error_handling;
mod formatting;
mod functions;
mod generics;
mod hashmaps;
mod hashsets;
mod hello_world;
mod io;
mod iterators;
mod lifetime;
mod methods;
mod modules;
mod options;
mod ownership;
mod pattern_matching;
mod reference_counter;
mod slices;
mod smart_pointers;
mod strings;
mod structs;
mod threads;
mod traits;
mod tuples;
mod unions;
mod variables;
mod vectors;

fn main() {
    hello_world::run();
    variables::run();
    conditions::run();
    variables::run();
    enumerations::run();
    unions::run();
    options::run();
    arrays::run();
    tuples::run();
    pattern_matching::run();
    generics::run();
    strings::run();
    hashmaps::run();
    hashsets::run();
    iterators::run();
    functions::run();
    methods::run();
    closures::run();
    traits::run();
    formatting::run();
    ownership::run();
    lifetime::run();
    reference_counter::run();
    atomic_reference_counter::run();
    threads::run();
    modules::run();
    error_handling::run();
    smart_pointers::run();
    bank::run();
    io::run();
    enums::run();
    slices::run();
}
