build:
  cargo build

check:
  cargo check

lint:
	cargo clippy

test t="": 
  @if [ -z "{{t}}" ]; then \
  cargo test; \
  else \
  cargo test "{{t}}" -- --nocapture; \
  fi;

run:
  cargo run

clean:
	cargo clean
