build:
	@echo "Building..."
	cargo build 

run:
	@echo "Running..."
	cargo run

check:
	@echo "check..."
	cargo check

clippy:
	@echo "Linting..."
	cargo clippy

clean:
	@echo "Cleaning..."
	cargo clean


test t="": 
    @if [ -z "{{t}}" ]; then \
    cargo test; \
    else \
    cargo test "{{t}}" -- --nocapture; \
    fi;

flake param="develop":
    @echo "Running flake recipe";
    @if [ "{{param}}" = "develop" ]; then \
    nix develop; \
    elif [ "{{param}}" = "allow" ]; then \
    direnv allow; \
    elif [ "{{param}}" = "disallow" ]; then \
    direnv disallow; \
    elif [ "{{param}}" = "clean" ]; then \
    rm flake.lock; \
    fi
